apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kvm-node-agent.fullname" . }}-metrics-reader
  labels:
  {{- include "kvm-node-agent.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get