apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kvm-node-agent.fullname" . }}-migration-editor-role
  labels:
  {{- include "kvm-node-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kvm.cloud.sap
  resources:
  - migrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvm.cloud.sap
  resources:
  - migrations/status
  verbs:
  - get
