apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kvm-node-agent
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kvm-node-agent
    app.kubernetes.io/managed-by: kustomize
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
      #  runAsNonRoot: true
        supplementalGroups:
          - 108 # libvirt group
      initContainers:
      - name: create-pki-dirs
        securityContext:
          runAsUser: 0
        image: busybox:1.28
        command: ['sh', '-c', 'cd /host/etc/pki && for i in CA libvirt qemu; do if [ -L ${i} ]; then rm ${i}; fi; done && mkdir -p CA libvirt qemu && chown 42438:42438 CA libvirt qemu && chmod 0755 CA libvirt qemu']
        volumeMounts:
        - mountPath: /host
          name: host
      containers:
      - command:
        - /manager
        args:
          - --health-probe-bind-address=:8081
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PKI_PATH
          value: /pki
        - name: HOST_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: ISSUER_NAME
          value: kvm-node-agent-ca-issuer
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /run/libvirt/libvirt-sock
          name: libvirt-sock
          readOnly: true
        - mountPath: /run/libvirt/libvirt-admin-sock
          name: libvirt-admin-sock
          readOnly: true
        - mountPath: /var/run/dbus/system_bus_socket
          name: systemd-sock
          readOnly: true
        - mountPath: /etc/os-release
          name: os-release
          readOnly: true
        - mountPath: /pki/CA
          name: pki-ca
        - mountPath: /pki/libvirt
          name: pki-libvirt
        - mountPath: /pki/qemu
          name: pki-qemu
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: libvirt-sock
        hostPath:
          path: /run/libvirt/libvirt-sock
          type: Socket
      - name: libvirt-admin-sock
        hostPath:
          path: /run/libvirt/libvirt-admin-sock
          type: Socket
      - name: systemd-sock
        hostPath:
          path: /run/dbus/system_bus_socket
          type: Socket
      - name: os-release
        hostPath:
          path: /etc/os-release
          type: File
      - name: pki-ca
        hostPath:
          path: /etc/pki/CA
          type: DirectoryOrCreate
      - name: pki-libvirt
        hostPath:
          path: /etc/pki/libvirt
          type: DirectoryOrCreate
      - name: pki-qemu
        hostPath:
          path: /etc/pki/qemu
          type: DirectoryOrCreate
      - name: host
        hostPath:
          path: /
