apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nova.openstack.cloud.sap/virt-driver
                operator: Exists
