// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package kernel

import (
	"sync"
)

// Ensure, that InterfaceMock does implement Interface.
// If this is not the case, regenerate this file with moq.
var _ Interface = &InterfaceMock{}

// InterfaceMock is a mock implementation of Interface.
//
//	func TestSomethingThatUsesInterface(t *testing.T) {
//
//		// make and configure a mocked Interface
//		mockedInterface := &InterfaceMock{
//			ReadParametersFunc: func() (*Parameters, error) {
//				panic("mock out the ReadParameters method")
//			},
//		}
//
//		// use mockedInterface in code that requires Interface
//		// and then make assertions.
//
//	}
type InterfaceMock struct {
	// ReadParametersFunc mocks the ReadParameters method.
	ReadParametersFunc func() (*Parameters, error)

	// calls tracks calls to the methods.
	calls struct {
		// ReadParameters holds details about calls to the ReadParameters method.
		ReadParameters []struct {
		}
	}
	lockReadParameters sync.RWMutex
}

// ReadParameters calls ReadParametersFunc.
func (mock *InterfaceMock) ReadParameters() (*Parameters, error) {
	if mock.ReadParametersFunc == nil {
		panic("InterfaceMock.ReadParametersFunc: method is nil but Interface.ReadParameters was just called")
	}
	callInfo := struct {
	}{}
	mock.lockReadParameters.Lock()
	mock.calls.ReadParameters = append(mock.calls.ReadParameters, callInfo)
	mock.lockReadParameters.Unlock()
	return mock.ReadParametersFunc()
}

// ReadParametersCalls gets all the calls that were made to ReadParameters.
// Check the length with:
//
//	len(mockedInterface.ReadParametersCalls())
func (mock *InterfaceMock) ReadParametersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockReadParameters.RLock()
	calls = mock.calls.ReadParameters
	mock.lockReadParameters.RUnlock()
	return calls
}
