// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package systemd

import (
	"context"
	v1 "github.com/cobaltcore-dev/openstack-hypervisor-operator/api/v1"
	systemd "github.com/coreos/go-systemd/v22/dbus"
	"sync"
)

// Ensure, that InterfaceMock does implement Interface.
// If this is not the case, regenerate this file with moq.
var _ Interface = &InterfaceMock{}

// InterfaceMock is a mock implementation of Interface.
//
//	func TestSomethingThatUsesInterface(t *testing.T) {
//
//		// make and configure a mocked Interface
//		mockedInterface := &InterfaceMock{
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//			DescribeFunc: func(ctx context.Context) (*Descriptor, error) {
//				panic("mock out the Describe method")
//			},
//			DisableShutdownInhibitFunc: func() error {
//				panic("mock out the DisableShutdownInhibit method")
//			},
//			EnableShutdownInhibitFunc: func(ctx context.Context, cb func(ctx2 context.Context) error) error {
//				panic("mock out the EnableShutdownInhibit method")
//			},
//			GetUnitByNameFunc: func(ctx context.Context, unit string) (systemd.UnitStatus, error) {
//				panic("mock out the GetUnitByName method")
//			},
//			IsConnectedFunc: func() bool {
//				panic("mock out the IsConnected method")
//			},
//			ListUnitsByNamesFunc: func(ctx context.Context, units []string) ([]systemd.UnitStatus, error) {
//				panic("mock out the ListUnitsByNames method")
//			},
//			ReconcileSysUpdateFunc: func(ctx context.Context, hv *v1.Hypervisor) (bool, error) {
//				panic("mock out the ReconcileSysUpdate method")
//			},
//			ReloadUnitFunc: func(ctx context.Context, unit string) (int, error) {
//				panic("mock out the ReloadUnit method")
//			},
//			StartUnitFunc: func(ctx context.Context, unit string) (int, error) {
//				panic("mock out the StartUnit method")
//			},
//		}
//
//		// use mockedInterface in code that requires Interface
//		// and then make assertions.
//
//	}
type InterfaceMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func()

	// DescribeFunc mocks the Describe method.
	DescribeFunc func(ctx context.Context) (*Descriptor, error)

	// DisableShutdownInhibitFunc mocks the DisableShutdownInhibit method.
	DisableShutdownInhibitFunc func() error

	// EnableShutdownInhibitFunc mocks the EnableShutdownInhibit method.
	EnableShutdownInhibitFunc func(ctx context.Context, cb func(ctx2 context.Context) error) error

	// GetUnitByNameFunc mocks the GetUnitByName method.
	GetUnitByNameFunc func(ctx context.Context, unit string) (systemd.UnitStatus, error)

	// IsConnectedFunc mocks the IsConnected method.
	IsConnectedFunc func() bool

	// ListUnitsByNamesFunc mocks the ListUnitsByNames method.
	ListUnitsByNamesFunc func(ctx context.Context, units []string) ([]systemd.UnitStatus, error)

	// ReconcileSysUpdateFunc mocks the ReconcileSysUpdate method.
	ReconcileSysUpdateFunc func(ctx context.Context, hv *v1.Hypervisor) (bool, error)

	// ReloadUnitFunc mocks the ReloadUnit method.
	ReloadUnitFunc func(ctx context.Context, unit string) (int, error)

	// StartUnitFunc mocks the StartUnit method.
	StartUnitFunc func(ctx context.Context, unit string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Describe holds details about calls to the Describe method.
		Describe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// DisableShutdownInhibit holds details about calls to the DisableShutdownInhibit method.
		DisableShutdownInhibit []struct {
		}
		// EnableShutdownInhibit holds details about calls to the EnableShutdownInhibit method.
		EnableShutdownInhibit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cb is the cb argument value.
			Cb func(ctx2 context.Context) error
		}
		// GetUnitByName holds details about calls to the GetUnitByName method.
		GetUnitByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Unit is the unit argument value.
			Unit string
		}
		// IsConnected holds details about calls to the IsConnected method.
		IsConnected []struct {
		}
		// ListUnitsByNames holds details about calls to the ListUnitsByNames method.
		ListUnitsByNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Units is the units argument value.
			Units []string
		}
		// ReconcileSysUpdate holds details about calls to the ReconcileSysUpdate method.
		ReconcileSysUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hv is the hv argument value.
			Hv *v1.Hypervisor
		}
		// ReloadUnit holds details about calls to the ReloadUnit method.
		ReloadUnit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Unit is the unit argument value.
			Unit string
		}
		// StartUnit holds details about calls to the StartUnit method.
		StartUnit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Unit is the unit argument value.
			Unit string
		}
	}
	lockClose                  sync.RWMutex
	lockDescribe               sync.RWMutex
	lockDisableShutdownInhibit sync.RWMutex
	lockEnableShutdownInhibit  sync.RWMutex
	lockGetUnitByName          sync.RWMutex
	lockIsConnected            sync.RWMutex
	lockListUnitsByNames       sync.RWMutex
	lockReconcileSysUpdate     sync.RWMutex
	lockReloadUnit             sync.RWMutex
	lockStartUnit              sync.RWMutex
}

// Close calls CloseFunc.
func (mock *InterfaceMock) Close() {
	if mock.CloseFunc == nil {
		panic("InterfaceMock.CloseFunc: method is nil but Interface.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedInterface.CloseCalls())
func (mock *InterfaceMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Describe calls DescribeFunc.
func (mock *InterfaceMock) Describe(ctx context.Context) (*Descriptor, error) {
	if mock.DescribeFunc == nil {
		panic("InterfaceMock.DescribeFunc: method is nil but Interface.Describe was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockDescribe.Lock()
	mock.calls.Describe = append(mock.calls.Describe, callInfo)
	mock.lockDescribe.Unlock()
	return mock.DescribeFunc(ctx)
}

// DescribeCalls gets all the calls that were made to Describe.
// Check the length with:
//
//	len(mockedInterface.DescribeCalls())
func (mock *InterfaceMock) DescribeCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockDescribe.RLock()
	calls = mock.calls.Describe
	mock.lockDescribe.RUnlock()
	return calls
}

// DisableShutdownInhibit calls DisableShutdownInhibitFunc.
func (mock *InterfaceMock) DisableShutdownInhibit() error {
	if mock.DisableShutdownInhibitFunc == nil {
		panic("InterfaceMock.DisableShutdownInhibitFunc: method is nil but Interface.DisableShutdownInhibit was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDisableShutdownInhibit.Lock()
	mock.calls.DisableShutdownInhibit = append(mock.calls.DisableShutdownInhibit, callInfo)
	mock.lockDisableShutdownInhibit.Unlock()
	return mock.DisableShutdownInhibitFunc()
}

// DisableShutdownInhibitCalls gets all the calls that were made to DisableShutdownInhibit.
// Check the length with:
//
//	len(mockedInterface.DisableShutdownInhibitCalls())
func (mock *InterfaceMock) DisableShutdownInhibitCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDisableShutdownInhibit.RLock()
	calls = mock.calls.DisableShutdownInhibit
	mock.lockDisableShutdownInhibit.RUnlock()
	return calls
}

// EnableShutdownInhibit calls EnableShutdownInhibitFunc.
func (mock *InterfaceMock) EnableShutdownInhibit(ctx context.Context, cb func(ctx2 context.Context) error) error {
	if mock.EnableShutdownInhibitFunc == nil {
		panic("InterfaceMock.EnableShutdownInhibitFunc: method is nil but Interface.EnableShutdownInhibit was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cb  func(ctx2 context.Context) error
	}{
		Ctx: ctx,
		Cb:  cb,
	}
	mock.lockEnableShutdownInhibit.Lock()
	mock.calls.EnableShutdownInhibit = append(mock.calls.EnableShutdownInhibit, callInfo)
	mock.lockEnableShutdownInhibit.Unlock()
	return mock.EnableShutdownInhibitFunc(ctx, cb)
}

// EnableShutdownInhibitCalls gets all the calls that were made to EnableShutdownInhibit.
// Check the length with:
//
//	len(mockedInterface.EnableShutdownInhibitCalls())
func (mock *InterfaceMock) EnableShutdownInhibitCalls() []struct {
	Ctx context.Context
	Cb  func(ctx2 context.Context) error
} {
	var calls []struct {
		Ctx context.Context
		Cb  func(ctx2 context.Context) error
	}
	mock.lockEnableShutdownInhibit.RLock()
	calls = mock.calls.EnableShutdownInhibit
	mock.lockEnableShutdownInhibit.RUnlock()
	return calls
}

// GetUnitByName calls GetUnitByNameFunc.
func (mock *InterfaceMock) GetUnitByName(ctx context.Context, unit string) (systemd.UnitStatus, error) {
	if mock.GetUnitByNameFunc == nil {
		panic("InterfaceMock.GetUnitByNameFunc: method is nil but Interface.GetUnitByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Unit string
	}{
		Ctx:  ctx,
		Unit: unit,
	}
	mock.lockGetUnitByName.Lock()
	mock.calls.GetUnitByName = append(mock.calls.GetUnitByName, callInfo)
	mock.lockGetUnitByName.Unlock()
	return mock.GetUnitByNameFunc(ctx, unit)
}

// GetUnitByNameCalls gets all the calls that were made to GetUnitByName.
// Check the length with:
//
//	len(mockedInterface.GetUnitByNameCalls())
func (mock *InterfaceMock) GetUnitByNameCalls() []struct {
	Ctx  context.Context
	Unit string
} {
	var calls []struct {
		Ctx  context.Context
		Unit string
	}
	mock.lockGetUnitByName.RLock()
	calls = mock.calls.GetUnitByName
	mock.lockGetUnitByName.RUnlock()
	return calls
}

// IsConnected calls IsConnectedFunc.
func (mock *InterfaceMock) IsConnected() bool {
	if mock.IsConnectedFunc == nil {
		panic("InterfaceMock.IsConnectedFunc: method is nil but Interface.IsConnected was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsConnected.Lock()
	mock.calls.IsConnected = append(mock.calls.IsConnected, callInfo)
	mock.lockIsConnected.Unlock()
	return mock.IsConnectedFunc()
}

// IsConnectedCalls gets all the calls that were made to IsConnected.
// Check the length with:
//
//	len(mockedInterface.IsConnectedCalls())
func (mock *InterfaceMock) IsConnectedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsConnected.RLock()
	calls = mock.calls.IsConnected
	mock.lockIsConnected.RUnlock()
	return calls
}

// ListUnitsByNames calls ListUnitsByNamesFunc.
func (mock *InterfaceMock) ListUnitsByNames(ctx context.Context, units []string) ([]systemd.UnitStatus, error) {
	if mock.ListUnitsByNamesFunc == nil {
		panic("InterfaceMock.ListUnitsByNamesFunc: method is nil but Interface.ListUnitsByNames was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Units []string
	}{
		Ctx:   ctx,
		Units: units,
	}
	mock.lockListUnitsByNames.Lock()
	mock.calls.ListUnitsByNames = append(mock.calls.ListUnitsByNames, callInfo)
	mock.lockListUnitsByNames.Unlock()
	return mock.ListUnitsByNamesFunc(ctx, units)
}

// ListUnitsByNamesCalls gets all the calls that were made to ListUnitsByNames.
// Check the length with:
//
//	len(mockedInterface.ListUnitsByNamesCalls())
func (mock *InterfaceMock) ListUnitsByNamesCalls() []struct {
	Ctx   context.Context
	Units []string
} {
	var calls []struct {
		Ctx   context.Context
		Units []string
	}
	mock.lockListUnitsByNames.RLock()
	calls = mock.calls.ListUnitsByNames
	mock.lockListUnitsByNames.RUnlock()
	return calls
}

// ReconcileSysUpdate calls ReconcileSysUpdateFunc.
func (mock *InterfaceMock) ReconcileSysUpdate(ctx context.Context, hv *v1.Hypervisor) (bool, error) {
	if mock.ReconcileSysUpdateFunc == nil {
		panic("InterfaceMock.ReconcileSysUpdateFunc: method is nil but Interface.ReconcileSysUpdate was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Hv  *v1.Hypervisor
	}{
		Ctx: ctx,
		Hv:  hv,
	}
	mock.lockReconcileSysUpdate.Lock()
	mock.calls.ReconcileSysUpdate = append(mock.calls.ReconcileSysUpdate, callInfo)
	mock.lockReconcileSysUpdate.Unlock()
	return mock.ReconcileSysUpdateFunc(ctx, hv)
}

// ReconcileSysUpdateCalls gets all the calls that were made to ReconcileSysUpdate.
// Check the length with:
//
//	len(mockedInterface.ReconcileSysUpdateCalls())
func (mock *InterfaceMock) ReconcileSysUpdateCalls() []struct {
	Ctx context.Context
	Hv  *v1.Hypervisor
} {
	var calls []struct {
		Ctx context.Context
		Hv  *v1.Hypervisor
	}
	mock.lockReconcileSysUpdate.RLock()
	calls = mock.calls.ReconcileSysUpdate
	mock.lockReconcileSysUpdate.RUnlock()
	return calls
}

// ReloadUnit calls ReloadUnitFunc.
func (mock *InterfaceMock) ReloadUnit(ctx context.Context, unit string) (int, error) {
	if mock.ReloadUnitFunc == nil {
		panic("InterfaceMock.ReloadUnitFunc: method is nil but Interface.ReloadUnit was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Unit string
	}{
		Ctx:  ctx,
		Unit: unit,
	}
	mock.lockReloadUnit.Lock()
	mock.calls.ReloadUnit = append(mock.calls.ReloadUnit, callInfo)
	mock.lockReloadUnit.Unlock()
	return mock.ReloadUnitFunc(ctx, unit)
}

// ReloadUnitCalls gets all the calls that were made to ReloadUnit.
// Check the length with:
//
//	len(mockedInterface.ReloadUnitCalls())
func (mock *InterfaceMock) ReloadUnitCalls() []struct {
	Ctx  context.Context
	Unit string
} {
	var calls []struct {
		Ctx  context.Context
		Unit string
	}
	mock.lockReloadUnit.RLock()
	calls = mock.calls.ReloadUnit
	mock.lockReloadUnit.RUnlock()
	return calls
}

// StartUnit calls StartUnitFunc.
func (mock *InterfaceMock) StartUnit(ctx context.Context, unit string) (int, error) {
	if mock.StartUnitFunc == nil {
		panic("InterfaceMock.StartUnitFunc: method is nil but Interface.StartUnit was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Unit string
	}{
		Ctx:  ctx,
		Unit: unit,
	}
	mock.lockStartUnit.Lock()
	mock.calls.StartUnit = append(mock.calls.StartUnit, callInfo)
	mock.lockStartUnit.Unlock()
	return mock.StartUnitFunc(ctx, unit)
}

// StartUnitCalls gets all the calls that were made to StartUnit.
// Check the length with:
//
//	len(mockedInterface.StartUnitCalls())
func (mock *InterfaceMock) StartUnitCalls() []struct {
	Ctx  context.Context
	Unit string
} {
	var calls []struct {
		Ctx  context.Context
		Unit string
	}
	mock.lockStartUnit.RLock()
	calls = mock.calls.StartUnit
	mock.lockStartUnit.RUnlock()
	return calls
}
