// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package systemd

import (
	"context"
	"github.com/cobaltcode-dev/kvm-node-agent/api/v1alpha1"
	"github.com/coreos/go-systemd/v22/dbus"
	"sync"
)

// Ensure, that InterfaceMock does implement Interface.
// If this is not the case, regenerate this file with moq.
var _ Interface = &InterfaceMock{}

// InterfaceMock is a mock implementation of Interface.
//
//	func TestSomethingThatUsesInterface(t *testing.T) {
//
//		// make and configure a mocked Interface
//		mockedInterface := &InterfaceMock{
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//			GetUnitByNameFunc: func(ctx context.Context, unit string) (dbus.UnitStatus, error) {
//				panic("mock out the GetUnitByName method")
//			},
//			IsConnectedFunc: func() bool {
//				panic("mock out the IsConnected method")
//			},
//			ListUnitsByNamesFunc: func(ctx context.Context, units []string) ([]dbus.UnitStatus, error) {
//				panic("mock out the ListUnitsByNames method")
//			},
//			ReconcileSysUpdateFunc: func(ctx context.Context, hv *v1alpha1.Hypervisor) (bool, error) {
//				panic("mock out the ReconcileSysUpdate method")
//			},
//			StartUnitFunc: func(ctx context.Context, unit string) (int, error) {
//				panic("mock out the StartUnit method")
//			},
//		}
//
//		// use mockedInterface in code that requires Interface
//		// and then make assertions.
//
//	}
type InterfaceMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func()

	// GetUnitByNameFunc mocks the GetUnitByName method.
	GetUnitByNameFunc func(ctx context.Context, unit string) (dbus.UnitStatus, error)

	// IsConnectedFunc mocks the IsConnected method.
	IsConnectedFunc func() bool

	// ListUnitsByNamesFunc mocks the ListUnitsByNames method.
	ListUnitsByNamesFunc func(ctx context.Context, units []string) ([]dbus.UnitStatus, error)

	// ReconcileSysUpdateFunc mocks the ReconcileSysUpdate method.
	ReconcileSysUpdateFunc func(ctx context.Context, hv *v1alpha1.Hypervisor) (bool, error)

	// StartUnitFunc mocks the StartUnit method.
	StartUnitFunc func(ctx context.Context, unit string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// GetUnitByName holds details about calls to the GetUnitByName method.
		GetUnitByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Unit is the unit argument value.
			Unit string
		}
		// IsConnected holds details about calls to the IsConnected method.
		IsConnected []struct {
		}
		// ListUnitsByNames holds details about calls to the ListUnitsByNames method.
		ListUnitsByNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Units is the units argument value.
			Units []string
		}
		// ReconcileSysUpdate holds details about calls to the ReconcileSysUpdate method.
		ReconcileSysUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hv is the hv argument value.
			Hv *v1alpha1.Hypervisor
		}
		// StartUnit holds details about calls to the StartUnit method.
		StartUnit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Unit is the unit argument value.
			Unit string
		}
	}
	lockClose              sync.RWMutex
	lockGetUnitByName      sync.RWMutex
	lockIsConnected        sync.RWMutex
	lockListUnitsByNames   sync.RWMutex
	lockReconcileSysUpdate sync.RWMutex
	lockStartUnit          sync.RWMutex
}

// Close calls CloseFunc.
func (mock *InterfaceMock) Close() {
	if mock.CloseFunc == nil {
		panic("InterfaceMock.CloseFunc: method is nil but Interface.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedInterface.CloseCalls())
func (mock *InterfaceMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// GetUnitByName calls GetUnitByNameFunc.
func (mock *InterfaceMock) GetUnitByName(ctx context.Context, unit string) (dbus.UnitStatus, error) {
	if mock.GetUnitByNameFunc == nil {
		panic("InterfaceMock.GetUnitByNameFunc: method is nil but Interface.GetUnitByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Unit string
	}{
		Ctx:  ctx,
		Unit: unit,
	}
	mock.lockGetUnitByName.Lock()
	mock.calls.GetUnitByName = append(mock.calls.GetUnitByName, callInfo)
	mock.lockGetUnitByName.Unlock()
	return mock.GetUnitByNameFunc(ctx, unit)
}

// GetUnitByNameCalls gets all the calls that were made to GetUnitByName.
// Check the length with:
//
//	len(mockedInterface.GetUnitByNameCalls())
func (mock *InterfaceMock) GetUnitByNameCalls() []struct {
	Ctx  context.Context
	Unit string
} {
	var calls []struct {
		Ctx  context.Context
		Unit string
	}
	mock.lockGetUnitByName.RLock()
	calls = mock.calls.GetUnitByName
	mock.lockGetUnitByName.RUnlock()
	return calls
}

// IsConnected calls IsConnectedFunc.
func (mock *InterfaceMock) IsConnected() bool {
	if mock.IsConnectedFunc == nil {
		panic("InterfaceMock.IsConnectedFunc: method is nil but Interface.IsConnected was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsConnected.Lock()
	mock.calls.IsConnected = append(mock.calls.IsConnected, callInfo)
	mock.lockIsConnected.Unlock()
	return mock.IsConnectedFunc()
}

// IsConnectedCalls gets all the calls that were made to IsConnected.
// Check the length with:
//
//	len(mockedInterface.IsConnectedCalls())
func (mock *InterfaceMock) IsConnectedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsConnected.RLock()
	calls = mock.calls.IsConnected
	mock.lockIsConnected.RUnlock()
	return calls
}

// ListUnitsByNames calls ListUnitsByNamesFunc.
func (mock *InterfaceMock) ListUnitsByNames(ctx context.Context, units []string) ([]dbus.UnitStatus, error) {
	if mock.ListUnitsByNamesFunc == nil {
		panic("InterfaceMock.ListUnitsByNamesFunc: method is nil but Interface.ListUnitsByNames was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Units []string
	}{
		Ctx:   ctx,
		Units: units,
	}
	mock.lockListUnitsByNames.Lock()
	mock.calls.ListUnitsByNames = append(mock.calls.ListUnitsByNames, callInfo)
	mock.lockListUnitsByNames.Unlock()
	return mock.ListUnitsByNamesFunc(ctx, units)
}

// ListUnitsByNamesCalls gets all the calls that were made to ListUnitsByNames.
// Check the length with:
//
//	len(mockedInterface.ListUnitsByNamesCalls())
func (mock *InterfaceMock) ListUnitsByNamesCalls() []struct {
	Ctx   context.Context
	Units []string
} {
	var calls []struct {
		Ctx   context.Context
		Units []string
	}
	mock.lockListUnitsByNames.RLock()
	calls = mock.calls.ListUnitsByNames
	mock.lockListUnitsByNames.RUnlock()
	return calls
}

// ReconcileSysUpdate calls ReconcileSysUpdateFunc.
func (mock *InterfaceMock) ReconcileSysUpdate(ctx context.Context, hv *v1alpha1.Hypervisor) (bool, error) {
	if mock.ReconcileSysUpdateFunc == nil {
		panic("InterfaceMock.ReconcileSysUpdateFunc: method is nil but Interface.ReconcileSysUpdate was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Hv  *v1alpha1.Hypervisor
	}{
		Ctx: ctx,
		Hv:  hv,
	}
	mock.lockReconcileSysUpdate.Lock()
	mock.calls.ReconcileSysUpdate = append(mock.calls.ReconcileSysUpdate, callInfo)
	mock.lockReconcileSysUpdate.Unlock()
	return mock.ReconcileSysUpdateFunc(ctx, hv)
}

// ReconcileSysUpdateCalls gets all the calls that were made to ReconcileSysUpdate.
// Check the length with:
//
//	len(mockedInterface.ReconcileSysUpdateCalls())
func (mock *InterfaceMock) ReconcileSysUpdateCalls() []struct {
	Ctx context.Context
	Hv  *v1alpha1.Hypervisor
} {
	var calls []struct {
		Ctx context.Context
		Hv  *v1alpha1.Hypervisor
	}
	mock.lockReconcileSysUpdate.RLock()
	calls = mock.calls.ReconcileSysUpdate
	mock.lockReconcileSysUpdate.RUnlock()
	return calls
}

// StartUnit calls StartUnitFunc.
func (mock *InterfaceMock) StartUnit(ctx context.Context, unit string) (int, error) {
	if mock.StartUnitFunc == nil {
		panic("InterfaceMock.StartUnitFunc: method is nil but Interface.StartUnit was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Unit string
	}{
		Ctx:  ctx,
		Unit: unit,
	}
	mock.lockStartUnit.Lock()
	mock.calls.StartUnit = append(mock.calls.StartUnit, callInfo)
	mock.lockStartUnit.Unlock()
	return mock.StartUnitFunc(ctx, unit)
}

// StartUnitCalls gets all the calls that were made to StartUnit.
// Check the length with:
//
//	len(mockedInterface.StartUnitCalls())
func (mock *InterfaceMock) StartUnitCalls() []struct {
	Ctx  context.Context
	Unit string
} {
	var calls []struct {
		Ctx  context.Context
		Unit string
	}
	mock.lockStartUnit.RLock()
	calls = mock.calls.StartUnit
	mock.lockStartUnit.RUnlock()
	return calls
}
